import { defineStore } from "pinia";
export const useUserStore=defineStore('user',{
    state:()=>({
            isLoggedIn:false,
            isRegister:false,
            isMusicWorld:true,
            isAllow:false,
            currentView:'combination',
            mmCurrentView:'myplaylists',
            currentCategory:'',
            currentCategoryIndex:0,
            playlistId:'',
            id:'',
            name:'游客',
            password:'',
            gender:'0',
            hobby:'无',
            token:''
    }),
    actions: {
        updateUserInfo(userInfo) {
            this.id=userInfo.id;
            this.token=userInfo.token;
            this.name=userInfo.name;
            this.gender=userInfo.gender;
            this.hobby=userInfo.hobby;
        },
        login(){
            this.isLoggedIn=true,
            this.isRegister=false
        },
        logout(){
            this.isLoggedIn=false,
            this.isRegister=false
        },
        switchToCombination(){
            this.isMusicWorld=true,
            this.currentView='combination'
        },
        switchToMymusic(){
            /* this.isMusicWorld=false
            if(this.isAllow===true){
                this.currentView='mymusic'
            }
            else{
                this.currentView='login'
            } */
            this.currentView='mymusic'
        },
        switchToRegister(){
            this.isLoggedIn=false,
            this.isRegister=true
        },
        editProfile(){
            this.currentView='editProfile'
        },
        switchToProfileCenter(){
            this.mmCurrentView='profilecenter'
        },
        switchToMyPlayLists(){
            this.mmCurrentView='myplaylists'
        },
        switchToPlayListDetail(value){
            this.isMusicWorld=true,
            this.currentView='playlistdetail',
            this.playlistId=value
        },
        changeCategory(value1,value2){
            this.currentCategory=value1;
            this.currentCategoryIndex=value2;
        },
        resetLoginSituation(){
            this.isLoggedIn=false,
            this.isRegister=false,
            this.isMusicWorld=false,
            this.isAllow=false,
            this.currentView='login',
            this.mmCurrentView='myplaylists',
            this.currentCategory='',
            this.id='',
            this.name='游客',
            this.gender='0',
            this.hobby='无',
            this.token=''
        }
    }
})